apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-app
  labels:
    app: backend-user-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user-app
  template:
    metadata:
      labels:
        app: backend-user-app
    spec:
      containers:
        - name: backend-user
          image: mhora1/udagram-api-user:v1
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: docker-secrets
